### ISSUE TITLE
Possibilidade de Jogar no proprio navegador

### ISSUE THREAD

**Issue by Maykon-JDS** [PedroMagno11/Detona-Ralph-JS#1]
Poderia hospedar o projeto através do GitHub Pages, isso possibilitaria rodar o jogo através de um site acessível pela Internet.

Abaixo deixo uma breve explicação da própria documentação do GitHub Pages:

"Você pode usar GitHub Pages para exibir alguns projetos de código aberto, hospedar um blogue ou até mesmo compartilhar seu currículo. Este guia ajudará você a começar a criar o seu próximo site."

Aqui está um link para a documentação do [GitHub Pages](https://docs.github.com/pt/pages): https://docs.github.com/pt/pages

**Comment by PedroMagno11** [comment]
Obrigado pela sugestão.
